CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI"

CREATE TABLE USER (
    ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50)
)

CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    INSERT INTO USER (NAME) VALUES (_NAME); 
END;

CALL spInsertUser('EMANUEL');

--MOSTRAR TODO
CREATE PROCEDURE `spFindAllUser`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USER; 
END

CALL spFindAllUser();

--MUESTRA UNO SOLO 

CREATE PROCEDURE `spFindUser`(IN `_ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
BEGIN 
    SELECT ID, NAME FROM USER WHERE ID = _ID; 
END;
CALL `spInsertUser`(1)

--MOSTRAR UNA ACTUALIZCION

CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT(5), IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER
 BEGIN 
    UPDATE USER SET NAME = _NAME WHERE ID = _ID; 
 END;

CALL spUpdateUser (1, "EMMANUEL");

 -- ELIMINA LOS DATOS

CREATE PROCEDURE `spDeleteUser`(IN `_ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER
    BEGIN DELETE FROM USER WHERE ID = _ID; 
END;

CALL spDeleteUser (3);